### ISSUE TITLE
model load error

### ISSUE THREAD

**Issue by wangshuo6699** [HillZhang1999/SynGEC#10]
当我离线加载模型时提示连接错误
![image](https://user-images.githubusercontent.com/36975782/204142962-8880bc2b-d717-4b65-981e-bbf55a0f7883.png)

**Comment by HillZhang1999** [comment]
请确认模型路径存在

**Comment by wangshuo6699** [comment]
模型从https://drive.google.com/file/d/1iei3TkFk2Onga2HHgPEP8CrbKaMKov5e/view?usp=sharing 这里下载，然后直接指定这个歌路径。请问我需要解压还是怎么操作呢？

**Comment by HillZhang1999** [comment]
直接下载，不需要解压。
你可以尝试下os.path.exists(path)，看看路径下是否存在对应的模型。

**Comment by wangshuo6699** [comment]
这个命令运行了，模型是存在的

**Comment by HillZhang1999** [comment]
此外，使用GOPar模型是需要验证ELECTRA的，这一步需要联网，可能你的服务器无法联网。请确认下

**Comment by wangshuo6699** [comment]
![image](https://user-images.githubusercontent.com/36975782/204145969-0ac937d6-c15e-431f-91ad-d92a8fc3b6da.png)
是在这个地方报的错，应该还没有到验证ELECTRA吧

**Comment by HillZhang1999** [comment]
你试试AutoTokenizer.from_pretrained("google/electra-large-discriminator")，看看能否成功

**Comment by wangshuo6699** [comment]
你好，我的服务器是没联网的，这个命令是有问题的。

**Comment by wangshuo6699** [comment]
请问，怎么可以离线加载呢？

**Comment by HillZhang1999** [comment]
提前下载好`google/electra-large-discriminator`并放到本地路径，然后将`bert`参数指定为该路径

**Comment by wrq9** [comment]
> 提前下载好`google/electra-large-discriminator`并放到本地路径，然后将`bert`参数指定为该路径

您好，请问bert参数在哪里修改？
