### ISSUE TITLE
关于推理clang8数据集遇到的问题

### ISSUE THREAD

**Issue by Laney-cici** [HillZhang1999/SynGEC#13]
您好！我现在想用您提供的syngec的bart模型推理一遍clang8的train数据集，遇到了以下两个问题，希望可以得到您的帮助。
1. 我在您发布的数据处理文件日志中发现clang8中train的数据条数为2372118条，但clang8官方发布的english数据有2372119条，似乎少了一条，请问是在处理的时候需要删除一条数据吗，这是否会导致数据对不齐？
![image](https://user-images.githubusercontent.com/82456281/205477859-e99cc764-062c-47b1-bef6-e419f0dd7abc.png)
![image](https://user-images.githubusercontent.com/82456281/205478017-7dddbf2f-41c1-470c-a816-c2db94d42615.png)

2. 在推理clang8的train数据集时遇到下面问题：
![image](https://user-images.githubusercontent.com/82456281/205477789-f6b0a814-3656-4d96-8360-fe628f90230f.png)
似乎参数buffersize不同，程序终止所读取的数据条数也不同，我不确定这是什么原因造成的，这是我的处理脚本：
![1](https://user-images.githubusercontent.com/82456281/205478408-c3c1722f-7cff-44a5-9596-32ac41c9d3b0.png)

**Comment by HillZhang1999** [comment]
1）我提供的CLang8数据仅供训练。可能是当时删除了某一条bad case数据，已经记不清了。如果推理的话，确实可能导致对不上。
2）第二个问题，syngec模型在推理超过buffersize长度的数据就是可能导致这个错误，记得当时是存在推理新buffer后句法信息对不上的潜在bug。但是一般的GEC测试数据规模都比较小，所以以前就没管了。后面如果有精力会修复下这个问题。
你可以先试着把buffer开大，sharding一下文件来推理。

**Comment by Laney-cici** [comment]
好的 感谢您的回复
