### ISSUE TITLE
关于max input length的问题

### ISSUE THREAD

**Issue by jiahaozhenbang** [HillZhang1999/SynGEC#19]
你好，感谢您开源了这么优秀的工作！

我想向您请教一个问题：

在论文中的**训练**细节里，我发现您提到max input length这个参数（=64 English）.
我想请问一下这个参数在哪里有体现呢，在训练脚本里面好像没有设置，是在数据预处理的时候就把超出长度的训练样本过滤掉了吗

**Comment by jiahaozhenbang** [comment]
感谢您的回复！

我看的是用预训练模型的训练脚本
[](https://github.com/HillZhang1999/SynGEC/blob/main/bash/english_exp/train_syngec_bart.sh)

这里好像没添加这个训练参数

**Comment by HillZhang1999** [comment]
你好，在这里指定了：https://github.com/HillZhang1999/SynGEC/blob/main/bash/english_exp/train_syngec_bart.sh#L198
这几个参数在限制句子长度这个层面都是一个意思

**Comment by jiahaozhenbang** [comment]
再次感谢您的回复！

所以在使用预训练模型的训练脚本（https://github.com/HillZhang1999/SynGEC/blob/main/bash/english_exp/train_syngec_bart.sh）中，**前面训练bart**时没有使用max-sentence-length，即没有限制句子长度，后面训练SynGEC才对句子长度做了约束，对吗

**Comment by HillZhang1999** [comment]
嗯嗯，你理解得是对的
