### ISSUE TITLE
Engineering efforts in Chinese GEC

### ISSUE THREAD

**Issue by wyxstriker** [HillZhang1999/SynGEC#24]
你好，我注意到本文中CGEC的bart单模型baseline在nlpcc18和mucgec数据集上指标相较于先前mucgec论文中指标均有接近5个点的提升，想一下这其中主要用到了哪些engineering efforts呢？

**Comment by wyxstriker** [comment]
主要就是src-drop么：）

**Comment by HillZhang1999** [comment]
还有就是扩充了词表

**Comment by wyxstriker** [comment]
了解了，感谢
