### ISSUE TITLE
Further Training 

### ISSUE THREAD

**Issue by yanghh2000** [HillZhang1999/SynGEC#31]
我想在已有checkpoint上训练其他数据集如FCGEC，那么GOPar需要重新训练吗？

**Comment by HillZhang1999** [comment]
训或不训都可以，但重新训练效果应该会好些

**Comment by yanghh2000** [comment]
请问是①先在第一阶段的模型上继续训练，然后再训第二阶段 or  ②直接在第二阶段上继续训

**Comment by yanghh2000** [comment]
另外，可以提供一下该模型fairseq格式转hugging face格式的脚本吗

**Comment by HillZhang1999** [comment]
> 请问是①先在第一阶段的模型上继续训练，然后再训第二阶段 or ②直接在第二阶段上继续训

两个都可以试试，我也不确定哪个更好，要根据实验结果看

**Comment by HillZhang1999** [comment]
> 另外，可以提供一下该模型fairseq格式转hugging face格式的脚本吗

可以参考：https://github.com/HillZhang1999/NaSGEC/blob/main/utils/convert_from_fairseq_to_huggingface.py

**Comment by yanghh2000** [comment]
> > 另外，可以提供一下该模型fairseq格式转hugging face格式的脚本吗
> 
> 可以参考：https://github.com/HillZhang1999/NaSGEC/blob/main/utils/convert_from_fairseq_to_huggingface.py

Traceback (most recent call last):
  File "convert_from_fairseq_to_huggingface.py", line 32, in <module>
    models, args, task = load_model_ensemble_and_task(filenames=[os.path.expanduser(main_args.checkpoint_path)],
  File "/data/yanghh/anaconda3/envs/fairseq/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/data/yanghh/anaconda3/envs/fairseq/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/data/yanghh/anaconda3/envs/fairseq/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 434, in _upgrade_state_dict
    registry.set_defaults(state["args"], tasks.TASK_REGISTRY[state["args"].task])
KeyError: 'syntax-enhanced-translation'

**Comment by HillZhang1999** [comment]
你需要先安装syngec的库，我们修改了原版的fairseq

**Comment by yanghh2000** [comment]
> 你需要先安装syngec的库，我们修改了原版的fairseq

对，我后面安装之后可以成功转换，但是转换过来的hf模型进行纠错时generate好像有点问题，会超过最大生成长度

**Comment by HillZhang1999** [comment]
> > 你需要先安装syngec的库，我们修改了原版的fairseq
> 
> 对，我后面安装之后可以成功转换，但是转换过来的hf模型进行纠错时generate好像有点问题，会超过最大生成长度

可能需要修改max_new_tokens这个参数？
