### ISSUE TITLE
convert_gec_data_to_parsing_data_chinese.py疑问

### ISSUE THREAD

**Issue by sunbo1999** [HillZhang1999/SynGEC#8]
`class Tree_Transformer:
    """根据m2格式信息完成句法树变形，需要提前提供Golden句法树

    Arguments:
        Errorifier {Class} -- 父类，仅做加噪
    """
    
    def __init__(self, sentence_conllx: list, m2: list):
        """构造函数

        Arguments:
            sentence_conllx {list} -- CoNLLx格式的句子
        """
        self.original_sentence = " ".join([t[1] for t in sentence_conllx])
        
        assert self.original_sentence == m2[0][2:], print(self.original_sentence, m2[0][2:])
        self.edits = m2[1:]
        self.original_conllx = copy.deepcopy(sentence_conllx)
        self.sentence = self.original_sentence
        self.conllx = sentence_conllx
        self.tokenized = None
        self.tokenize()
        self.parse_conllx()`
其中，sentence_conllx是CoNLLx格式的句子，是stanza依存分析后的结果，格式如下：
1	他	_	_	_	_	2	nsubj	_	_
2	是	_	_	_	_	0	root	_	_
3	个	_	_	_	_	8	clf	_	_
4	很	_	_	_	_	6	advmod	_	_
5	要	_	_	_	_	8	rcmod	_	_
6	强	_	_	_	_	8	rcmod	_	_
7	的	_	_	_	_	5	cpm	_	_
8	人	_	_	_	_	2	attr	_	_
9	，	_	_	_	_	2	punct	_	_
10	想	_	_	_	_	2	conj	_	_
11	不到	_	_	_	_	10	dep	_	_
12	被	_	_	_	_	16	pass	_	_
13	这	_	_	_	_	15	det	_	_
14	个	_	_	_	_	13	clf	_	_
15	问题	_	_	_	_	16	nsubj	_	_
16	难住	_	_	_	_	10	dep	_	_
17	了	_	_	_	_	16	asp	_	_
18	。	_	_	_	_	2	punct	_	_
那么，original_sentence应该是整个句子分词后，按照空格连接一起；而m2是按照字符级别的编辑操作，格式如下：
S 他 是 个 很 要 强 的 人 ， 想 不 到 被 这 个 问 题 难 住 了 。
T0-A0 他 是 个 很 要 强 的 人 ， 想 不 到 被 这 个 问 题 把 他 难 住 了 。
A 17 17|||M|||把 他|||REQUIRED|||-NONE-|||0
所以，original_sentence不可能和 m2[0][2:]是一样的，是代码存在什么问题，还是我哪个地方数据处理出了问题？

**Comment by HillZhang1999** [comment]
Sorry，我们的流程写得可能有点不清楚。

**Comment by HillZhang1999** [comment]
您也可以自己重新训练一个字级别off-the-shelf parser（比如用stanza），只需要先把原始的CTB语料用：https://github.com/HillZhang1999/SynGEC/blob/main/utils/convert_chinese_treebank_from_word_to_char.py
转成字级别，再用相同的参数在新的字级别CTB上训练即可。

**Comment by sunbo1999** [comment]
您好，训练好的字符级别off-the-shelf parser会提供吗

**Comment by HillZhang1999** [comment]
> 您好，训练好的字符级别off-the-shelf parser会提供吗

明晚之前会上传

**Comment by sunbo1999** [comment]
好的，感谢回复

**Comment by sunbo1999** [comment]
您好，我这边加载biaffine-dep-electra-zh-char存在一点问题
`from supar import Parser

# path = './emnlp2022_syngec_biaffine-dep-electra-zh-gopar'
path = './emnlp2022_syngec_biaffine-dep-electra-zh-char'
dep = Parser.load(path)
res = dep.predict("语法纠错", verbose=False, lang='zh', prob=True)`
报错如下：
`AttributeError: Can't get attribute 'AttachmentMetricWithGED' on <module 'supar.utils.metric'`
同样的方式加载您之前发布的biaffine-dep-electra-zh-gopar就没问题，请问是您模型那边上传的有什么问题吗？还是我这边加载模型有什么问题呢？

**Comment by sunbo1999** [comment]
另外，我发现，如果输入的中文是按空格分隔的句子，依存分析的结果就是字级别的，不知道这种处理和您之前说的字符级别off-the-shelf parser是否等效？
```
dep = Parser.load("biaffine-dep-electra-zh")
res = dep.predict("他 是 个 很 要 强 的 人 ， 想 不 到 被 这 个 问 题 难 住 了 。", verbose=False, lang='zh', prob=True)
print(type(res))
print(str(res[0]))
```
 
1       他      _       _       _       _       2       nsubj   _       _
2       是      _       _       _       _       0       root    _       _
3       个      _       _       _       _       8       clf     _       _
4       很      _       _       _       _       6       advmod  _       _
5       要      _       _       _       _       8       rcmod   _       _
6       强      _       _       _       _       8       rcmod   _       _
7       的      _       _       _       _       5       cpm     _       _
8       人      _       _       _       _       2       attr    _       _
9       ，      _       _       _       _       2       punct   _       _
10      想      _       _       _       _       2       conj    _       _
11      不      _       _       _       _       10      dep     _       _
12      到      _       _       _       _       10      dep     _       _
13      被      _       _       _       _       18      pass    _       _
14      这      _       _       _       _       17      det     _       _
15      个      _       _       _       _       14      clf     _       _
16      问      _       _       _       _       17      nn      _       _
17      题      _       _       _       _       18      nsubj   _       _
18      难      _       _       _       _       10      dep     _       _
19      住      _       _       _       _       18      rcomp   _       _
20      了      _       _       _       _       18      asp     _       _
21      。      _       _       _       _       2       punct   _       _

**Comment by HillZhang1999** [comment]
> 另外，我发现，如果输入的中文是按空格分隔的句子，依存分析的结果就是字级别的，不知道这种处理和您之前说的字符级别off-the-shelf parser是否等效？
> 
> ```
> dep = Parser.load("biaffine-dep-electra-zh")
> res = dep.predict("他 是 个 很 要 强 的 人 ， 想 不 到 被 这 个 问 题 难 住 了 。", verbose=False, lang='zh', prob=True)
> ```
> 
> 1 他 _ _ _ _ 2 nsubj _ _ 2 是 _ _ _ _ 0 root _ _ 3 个 _ _ _ _ 8 clf _ _ 4 很 _ _ _ _ 6 advmod _ _ 5 要 _ _ _ _ 8 rcmod _ _ 6 强 _ _ _ _ 8 rcmod _ _ 7 的 _ _ _ _ 5 cpm _ _ 8 人 _ _ _ _ 2 attr _ _ 9 ， _ _ _ _ 2 punct _ _ 10 想 _ _ _ _ 2 conj _ _ 11 不 _ _ _ _ 10 dep _ _ 12 到 _ _ _ _ 10 dep _ _ 13 被 _ _ _ _ 18 pass _ _ 14 这 _ _ _ _ 17 det _ _ 15 个 _ _ _ _ 14 clf _ _ 16 问 _ _ _ _ 17 nn _ _ 17 题 _ _ _ _ 18 nsubj _ _ 18 难 _ _ _ _ 10 dep _ _ 19 住 _ _ _ _ 18 rcomp _ _ 20 了 _ _ _ _ 18 asp _ _ 21 。 _ _ _ _ 2 punct _ _

这个parser训练时是词级别的，输入强行是字级别的话结果可能是不正确的。

**Comment by HillZhang1999** [comment]
> 您好，我这边加载biaffine-dep-electra-zh-char存在一点问题
> 
> ```
> from supar import Parser
> path = './emnlp2022_syngec_biaffine-dep-electra-zh-gopar'
> path = './emnlp2022_syngec_biaffine-dep-electra-zh-char'
> dep = Parser.load(path)
> res = dep.predict("语法纠错", verbose=False, lang='zh', prob=True)
> ```
> 
> 报错如下： `AttributeError: Can't get attribute 'AttachmentMetricWithGED' on <module 'supar.utils.metric'` 同样的方式加载您之前发布的biaffine-dep-electra-zh-gopar就没问题，请问是您模型那边上传的有什么问题吗？还是我这边加载模型有什么问题呢？

您好，刚刚复现了下，这确实是一个bug。
解决方案是：请您在`AttributeError: Can't get attribute 'AttachmentMetricWithGED' on <module 'supar.utils.metric' from '/home/pai/envs/test/lib/python3.8/site-packages/supar/utils/metric.py'>`

**Comment by sunbo1999** [comment]
您好，我这边加载biaffine-dep-electra-zh-char模型之后的输出，好像还不是完全的字级别的

```
path = './emnlp2022_syngec_biaffine-dep-electra-zh-char'
dep = Parser.load(path)
res = dep.predict(["大 型 国 营 企 业 发 生 的 损 失 ， 很 大 程 度 上 是 与 企 业 内 控 制 机 制 缺 失 ， 监 督 管 理 不 严 有 关 。"], verbose=False, lang='zh', prob=True)


```
1       大      _       _       _       _       2       app     _       _
2       型      _       _       _       _       6       amod    _       _
3       国      _       _       _       _       4       app     _       _
4       营      _       _       _       _       6       amod    _       _
5       企      _       _       _       _       6       app     _       _
6       业      _       _       _       _       8       nsubj   _       _
7       发      _       _       _       _       8       app     _       _
8       生      _       _       _       _       11      rcmod   _       _
9       的      _       _       _       _       8       cpm     _       _
10      损      _       _       _       _       11      app     _       _
11      失 ，   _       _       _       _       33      punct   _       _
12      很      _       _       _       _       13      app     _       _
13      大 程   _       _       _       _       14      app     _       _
14      度      _       _       _       _       15      lobj    _       _
15      上 是   _       _       _       _       33      loc     _       _
16      与      _       _       _       _       33      prep    _       _
17      企      _       _       _       _       18      app     _       _
18      业      _       _       _       _       19      lobj    _       _
19      内      _       _       _       _       23      dep     _       _
20      控      _       _       _       _       21      app     _       _
21      制      _       _       _       _       23      nn      _       _
22      机      _       _       _       _       23      app     _       _
23      制      _       _       _       _       25      nsubj   _       _
24      缺      _       _       _       _       25      app     _       _
25      失      _       _       _       _       16      pccomp  _       _
26      ，      _       _       _       _       25      punct   _       _
27      监      _       _       _       _       28      app     _       _
28      督      _       _       _       _       30      nn      _       _
29      管      _       _       _       _       30      app     _       _
30      理      _       _       _       _       31      nsubj   _       _
31      不 严   _       _       _       _       25      conj    _       _
32      有      _       _       _       _       33      app     _       _
33      关      _       _       _       _       0       root    _       _
34      。      _       _       _       _       33      punct   _       _

> 但需要注意，stanza预测时，分词（字）粒度一定要和m2是一致的，即先分字（用[segment_bert](https://github.com/HillZhang1999/SynGEC/blob/main/utils/segment_bert.py)），再做parsing，不然还是会出现您说的mismatch的现象。
参考您之前的提醒，我这里面已经是分字了，就是句子按照空格分隔，但是结果还是有词级别的？
